### PR TITLE
fixed #34 support for detaching from terminal, and this as default

### LINKED ISSUE #34: Detach from terminal?
Hi! Great project!

I often use "neoray" in the terminal (alacritty), which is blocked after startup:
```bash
» neoray
[TRACE] [NVIM] Neovim version 0.7.0
[TRACE] [NEORAY] Glfw version: 3.3.4 X11 GLX EGL OSMesa clock_gettime evdev
[TRACE] [RENDERER] Opengl Version: 4.6 (Core Profile) Mesa 22.1.2
[TRACE] [PERFORMANCE] Start time: 141.210204ms
[ERROR] [NEORAY] Assertion Failed: print() function used in release build
Grid.Resize, ID: 1 Rows: 33 Cols: 88
[TRACE] [NEORAY] Regular: UbuntuMono-R.ttf
[TRACE] [NEORAY] Bold Italic: UbuntuMono-BI.ttf
[TRACE] [NEORAY] Italic: UbuntuMono-RI.ttf
[TRACE] [NEORAY] Bold: UbuntuMono-B.ttf
[ERROR] [NEORAY] Assertion Failed: print() function used in release build
Grid.Resize, ID: 1 Rows: 40 Cols: 114
[ERROR] [NEORAY] Assertion Failed: print() function used in release build
Grid.Resize, ID: 1 Rows: 94 Cols: 81
```
Is it possible to prevent this?

Currently I use a "wrapper" (`gvim`):
```bash
#!/usr/bin/env bash
neoray "$@" > /dev/null 2>&1 &
disown %1
```

### PR DESCRIPTION
**Pull request by TianYaX**
Detach from terminal on `linux` or `darwin`.

### CODE REVIEW

**Review by hismailbulut — CHANGES_REQUESTED** [review]
Thanks for your work but there is an issue I think parent() function doesn't check for --nofork option and always forks
And there are some design issues in my opinion
I think better approach is instead of creating a new file and functions for this you can check options.nofork at the end of the ProcessBefore and runtime check the OS and fork or not fork here, also return true for quit instead of checking in main

**Comment by hismailbulut** [comment]
Sorry it actually checks for nofork, but design problem continues.

**Comment by TianYaX** [comment]
> Thanks for your work but there is an issue I think parent() function doesn't check for --nofork option and always forks
> And there are some design issues in my opinion
> I think better approach is instead of creating a new file and functions for this you can check options.nofork at the end of the ParseArgs and runtime check the OS and fork or not fork here, also return true for quit instead of checking in main

Great idea!  I'll try to make some changes, thanks!

**Review by hismailbulut — APPROVED** [review]
Nice and clean 👌
Thank you

**Pull request merged**
